version: 'latest'

services:
  # db service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    networks:
      - test_network
  # web app
  api:
    image: taskmanagerapi:latest
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=localhost;Database=todoapp;Username=postgres;Password=postgres;Port=5432
    ports:
      - "5000:80"
    command: ["dotnet", "test", "TaskManagerAPI.Tests/TaskManagerAPI.Tests.csproj"]

networks:
  test_network:
    driver: bridge